"""increase password_hash width

Revision ID: 577b57441dec
Revises: 8eb1726549a3
Create Date: 2025-12-22 14:13:40.936213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577b57441dec'
down_revision = '8eb1726549a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
